ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS irn VARCHAR(100) DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS irn_generated_at TIMESTAMP DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS ack_no VARCHAR(50) DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS ack_date TIMESTAMP DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS signed_invoice TEXT DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS signed_qr_code TEXT DEFAULT NULL;
ALTER TABLE hris_saas.invoices ADD COLUMN IF NOT EXISTS irn_cancel_date TIMESTAMP DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_invoices_irn ON hris_saas.invoices (irn);
