CREATE TABLE IF NOT EXISTS hris_saas.unit_master (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO hris_saas.unit_master (id, name, description, is_active, display_order) VALUES
('unit-01', 'Nos',     'Number of items', true, 1),
('unit-02', 'Unit',    'Per unit', true, 2),
('unit-03', 'Piece',   'Individual piece', true, 3),
('unit-04', 'Pair',    'Pair of items', true, 4),
('unit-05', 'Set',     'Set of items', true, 5),
('unit-06', 'Pack',    'Pack of items', true, 6),
('unit-07', 'Box',     'Box of items', true, 7),
('unit-08', 'Carton',  'Carton of items', true, 8),
('unit-09', 'Case',    'Case of items', true, 9),
('unit-10', 'Dozen',   'Dozen (12 items)', true, 10),
('unit-11', 'Bottle',  'Bottle', true, 11),
('unit-12', 'Jar',     'Jar', true, 12),
('unit-13', 'Can',     'Can', true, 13),
('unit-14', 'Tube',    'Tube', true, 14),
('unit-15', 'Packet',  'Packet of items', true, 15),
('unit-16', 'Bag',     'Bag of items', true, 16),
('unit-17', 'Bundle',  'Bundle of items', true, 17),
('unit-18', 'Roll',    'Roll', true, 18),
('unit-19', 'Sheet',   'Sheet', true, 19),
('unit-20', 'Kg',      'Kilogram', true, 20),
('unit-21', 'Gram',    'Gram', true, 21),
('unit-22', 'Ton',     'Metric ton', true, 22),
('unit-23', 'Liter',   'Litre', true, 23),
('unit-24', 'Ml',      'Millilitre', true, 24),
('unit-25', 'Meter',   'Metre', true, 25),
('unit-26', 'Cm',      'Centimetre', true, 26),
('unit-27', 'Foot',    'Foot', true, 27),
('unit-28', 'Inch',    'Inch', true, 28),
('unit-29', 'Sq Ft',   'Square foot', true, 29),
('unit-30', 'Sq Meter','Square metre', true, 30),
('unit-31', 'Tablet',  'Tablet', true, 31),
('unit-32', 'Capsule', 'Capsule', true, 32),
('unit-33', 'Strip',   'Strip of tablets', true, 33),
('unit-34', 'Pallet',  'Pallet of items', true, 34),
('unit-35', 'Container','Shipping container', true, 35)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, is_active=EXCLUDED.is_active, display_order=EXCLUDED.display_order;
